save_dir: train_vertex 
data:
  name: nexo
  h5name: /expanse/lustre/scratch/zli10/temp_project/vertex/nexo.h5
  csv: /expanse/lustre/scratch/zli10/temp_project/vertex/nexo.csv
  input_shape:
  - 200
  - 255
  - 2
model:
  name: resnet18

fit:
  compile:
    initial_lr: 0.001
    lr_decay: 0.99
    optimizer: Adam
    loss: MSE 
  epochs: 20
  patience: 1000
  batch_size: 200

